// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SimulationsColumns holds the columns for the "simulations" table.
	SimulationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "amount", Type: field.TypeFloat64},
		{Name: "interest", Type: field.TypeFloat64},
		{Name: "periods", Type: field.TypeFloat64},
		{Name: "monthly_payment", Type: field.TypeFloat64},
		{Name: "created_at", Type: field.TypeTime},
	}
	// SimulationsTable holds the schema information for the "simulations" table.
	SimulationsTable = &schema.Table{
		Name:       "simulations",
		Columns:    SimulationsColumns,
		PrimaryKey: []*schema.Column{SimulationsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SimulationsTable,
	}
)

func init() {
}
