// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/atamayoz/credit-go/ent/predicate"
	"github.com/atamayoz/credit-go/ent/simulation"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeSimulation = "Simulation"
)

// SimulationMutation represents an operation that mutates the Simulation nodes in the graph.
type SimulationMutation struct {
	config
	op                 Op
	typ                string
	id                 *int
	amount             *float64
	addamount          *float64
	interest           *float64
	addinterest        *float64
	periods            *float64
	addperiods         *float64
	monthly_payment    *float64
	addmonthly_payment *float64
	created_at         *time.Time
	clearedFields      map[string]struct{}
	done               bool
	oldValue           func(context.Context) (*Simulation, error)
	predicates         []predicate.Simulation
}

var _ ent.Mutation = (*SimulationMutation)(nil)

// simulationOption allows management of the mutation configuration using functional options.
type simulationOption func(*SimulationMutation)

// newSimulationMutation creates new mutation for the Simulation entity.
func newSimulationMutation(c config, op Op, opts ...simulationOption) *SimulationMutation {
	m := &SimulationMutation{
		config:        c,
		op:            op,
		typ:           TypeSimulation,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSimulationID sets the ID field of the mutation.
func withSimulationID(id int) simulationOption {
	return func(m *SimulationMutation) {
		var (
			err   error
			once  sync.Once
			value *Simulation
		)
		m.oldValue = func(ctx context.Context) (*Simulation, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Simulation.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSimulation sets the old Simulation of the mutation.
func withSimulation(node *Simulation) simulationOption {
	return func(m *SimulationMutation) {
		m.oldValue = func(context.Context) (*Simulation, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SimulationMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SimulationMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SimulationMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SimulationMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Simulation.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetAmount sets the "amount" field.
func (m *SimulationMutation) SetAmount(f float64) {
	m.amount = &f
	m.addamount = nil
}

// Amount returns the value of the "amount" field in the mutation.
func (m *SimulationMutation) Amount() (r float64, exists bool) {
	v := m.amount
	if v == nil {
		return
	}
	return *v, true
}

// OldAmount returns the old "amount" field's value of the Simulation entity.
// If the Simulation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SimulationMutation) OldAmount(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAmount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAmount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAmount: %w", err)
	}
	return oldValue.Amount, nil
}

// AddAmount adds f to the "amount" field.
func (m *SimulationMutation) AddAmount(f float64) {
	if m.addamount != nil {
		*m.addamount += f
	} else {
		m.addamount = &f
	}
}

// AddedAmount returns the value that was added to the "amount" field in this mutation.
func (m *SimulationMutation) AddedAmount() (r float64, exists bool) {
	v := m.addamount
	if v == nil {
		return
	}
	return *v, true
}

// ResetAmount resets all changes to the "amount" field.
func (m *SimulationMutation) ResetAmount() {
	m.amount = nil
	m.addamount = nil
}

// SetInterest sets the "interest" field.
func (m *SimulationMutation) SetInterest(f float64) {
	m.interest = &f
	m.addinterest = nil
}

// Interest returns the value of the "interest" field in the mutation.
func (m *SimulationMutation) Interest() (r float64, exists bool) {
	v := m.interest
	if v == nil {
		return
	}
	return *v, true
}

// OldInterest returns the old "interest" field's value of the Simulation entity.
// If the Simulation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SimulationMutation) OldInterest(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInterest is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInterest requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInterest: %w", err)
	}
	return oldValue.Interest, nil
}

// AddInterest adds f to the "interest" field.
func (m *SimulationMutation) AddInterest(f float64) {
	if m.addinterest != nil {
		*m.addinterest += f
	} else {
		m.addinterest = &f
	}
}

// AddedInterest returns the value that was added to the "interest" field in this mutation.
func (m *SimulationMutation) AddedInterest() (r float64, exists bool) {
	v := m.addinterest
	if v == nil {
		return
	}
	return *v, true
}

// ResetInterest resets all changes to the "interest" field.
func (m *SimulationMutation) ResetInterest() {
	m.interest = nil
	m.addinterest = nil
}

// SetPeriods sets the "periods" field.
func (m *SimulationMutation) SetPeriods(f float64) {
	m.periods = &f
	m.addperiods = nil
}

// Periods returns the value of the "periods" field in the mutation.
func (m *SimulationMutation) Periods() (r float64, exists bool) {
	v := m.periods
	if v == nil {
		return
	}
	return *v, true
}

// OldPeriods returns the old "periods" field's value of the Simulation entity.
// If the Simulation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SimulationMutation) OldPeriods(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPeriods is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPeriods requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPeriods: %w", err)
	}
	return oldValue.Periods, nil
}

// AddPeriods adds f to the "periods" field.
func (m *SimulationMutation) AddPeriods(f float64) {
	if m.addperiods != nil {
		*m.addperiods += f
	} else {
		m.addperiods = &f
	}
}

// AddedPeriods returns the value that was added to the "periods" field in this mutation.
func (m *SimulationMutation) AddedPeriods() (r float64, exists bool) {
	v := m.addperiods
	if v == nil {
		return
	}
	return *v, true
}

// ResetPeriods resets all changes to the "periods" field.
func (m *SimulationMutation) ResetPeriods() {
	m.periods = nil
	m.addperiods = nil
}

// SetMonthlyPayment sets the "monthly_payment" field.
func (m *SimulationMutation) SetMonthlyPayment(f float64) {
	m.monthly_payment = &f
	m.addmonthly_payment = nil
}

// MonthlyPayment returns the value of the "monthly_payment" field in the mutation.
func (m *SimulationMutation) MonthlyPayment() (r float64, exists bool) {
	v := m.monthly_payment
	if v == nil {
		return
	}
	return *v, true
}

// OldMonthlyPayment returns the old "monthly_payment" field's value of the Simulation entity.
// If the Simulation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SimulationMutation) OldMonthlyPayment(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMonthlyPayment is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMonthlyPayment requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMonthlyPayment: %w", err)
	}
	return oldValue.MonthlyPayment, nil
}

// AddMonthlyPayment adds f to the "monthly_payment" field.
func (m *SimulationMutation) AddMonthlyPayment(f float64) {
	if m.addmonthly_payment != nil {
		*m.addmonthly_payment += f
	} else {
		m.addmonthly_payment = &f
	}
}

// AddedMonthlyPayment returns the value that was added to the "monthly_payment" field in this mutation.
func (m *SimulationMutation) AddedMonthlyPayment() (r float64, exists bool) {
	v := m.addmonthly_payment
	if v == nil {
		return
	}
	return *v, true
}

// ResetMonthlyPayment resets all changes to the "monthly_payment" field.
func (m *SimulationMutation) ResetMonthlyPayment() {
	m.monthly_payment = nil
	m.addmonthly_payment = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *SimulationMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *SimulationMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Simulation entity.
// If the Simulation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SimulationMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *SimulationMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the SimulationMutation builder.
func (m *SimulationMutation) Where(ps ...predicate.Simulation) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SimulationMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SimulationMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Simulation, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SimulationMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SimulationMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Simulation).
func (m *SimulationMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SimulationMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.amount != nil {
		fields = append(fields, simulation.FieldAmount)
	}
	if m.interest != nil {
		fields = append(fields, simulation.FieldInterest)
	}
	if m.periods != nil {
		fields = append(fields, simulation.FieldPeriods)
	}
	if m.monthly_payment != nil {
		fields = append(fields, simulation.FieldMonthlyPayment)
	}
	if m.created_at != nil {
		fields = append(fields, simulation.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SimulationMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case simulation.FieldAmount:
		return m.Amount()
	case simulation.FieldInterest:
		return m.Interest()
	case simulation.FieldPeriods:
		return m.Periods()
	case simulation.FieldMonthlyPayment:
		return m.MonthlyPayment()
	case simulation.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SimulationMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case simulation.FieldAmount:
		return m.OldAmount(ctx)
	case simulation.FieldInterest:
		return m.OldInterest(ctx)
	case simulation.FieldPeriods:
		return m.OldPeriods(ctx)
	case simulation.FieldMonthlyPayment:
		return m.OldMonthlyPayment(ctx)
	case simulation.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Simulation field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SimulationMutation) SetField(name string, value ent.Value) error {
	switch name {
	case simulation.FieldAmount:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAmount(v)
		return nil
	case simulation.FieldInterest:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInterest(v)
		return nil
	case simulation.FieldPeriods:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPeriods(v)
		return nil
	case simulation.FieldMonthlyPayment:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMonthlyPayment(v)
		return nil
	case simulation.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Simulation field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SimulationMutation) AddedFields() []string {
	var fields []string
	if m.addamount != nil {
		fields = append(fields, simulation.FieldAmount)
	}
	if m.addinterest != nil {
		fields = append(fields, simulation.FieldInterest)
	}
	if m.addperiods != nil {
		fields = append(fields, simulation.FieldPeriods)
	}
	if m.addmonthly_payment != nil {
		fields = append(fields, simulation.FieldMonthlyPayment)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SimulationMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case simulation.FieldAmount:
		return m.AddedAmount()
	case simulation.FieldInterest:
		return m.AddedInterest()
	case simulation.FieldPeriods:
		return m.AddedPeriods()
	case simulation.FieldMonthlyPayment:
		return m.AddedMonthlyPayment()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SimulationMutation) AddField(name string, value ent.Value) error {
	switch name {
	case simulation.FieldAmount:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAmount(v)
		return nil
	case simulation.FieldInterest:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddInterest(v)
		return nil
	case simulation.FieldPeriods:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPeriods(v)
		return nil
	case simulation.FieldMonthlyPayment:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddMonthlyPayment(v)
		return nil
	}
	return fmt.Errorf("unknown Simulation numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SimulationMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SimulationMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SimulationMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Simulation nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SimulationMutation) ResetField(name string) error {
	switch name {
	case simulation.FieldAmount:
		m.ResetAmount()
		return nil
	case simulation.FieldInterest:
		m.ResetInterest()
		return nil
	case simulation.FieldPeriods:
		m.ResetPeriods()
		return nil
	case simulation.FieldMonthlyPayment:
		m.ResetMonthlyPayment()
		return nil
	case simulation.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown Simulation field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SimulationMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SimulationMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SimulationMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SimulationMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SimulationMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SimulationMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SimulationMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Simulation unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SimulationMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Simulation edge %s", name)
}
