// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/atamayoz/credit-go/ent/schema"
	"github.com/atamayoz/credit-go/ent/simulation"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	simulationFields := schema.Simulation{}.Fields()
	_ = simulationFields
	// simulationDescCreatedAt is the schema descriptor for created_at field.
	simulationDescCreatedAt := simulationFields[4].Descriptor()
	// simulation.DefaultCreatedAt holds the default value on creation for the created_at field.
	simulation.DefaultCreatedAt = simulationDescCreatedAt.Default.(func() time.Time)
}
