// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/atamayoz/credit-go/ent/simulation"
)

// SimulationCreate is the builder for creating a Simulation entity.
type SimulationCreate struct {
	config
	mutation *SimulationMutation
	hooks    []Hook
}

// SetAmount sets the "amount" field.
func (sc *SimulationCreate) SetAmount(f float64) *SimulationCreate {
	sc.mutation.SetAmount(f)
	return sc
}

// SetInterest sets the "interest" field.
func (sc *SimulationCreate) SetInterest(f float64) *SimulationCreate {
	sc.mutation.SetInterest(f)
	return sc
}

// SetPeriods sets the "periods" field.
func (sc *SimulationCreate) SetPeriods(f float64) *SimulationCreate {
	sc.mutation.SetPeriods(f)
	return sc
}

// SetMonthlyPayment sets the "monthly_payment" field.
func (sc *SimulationCreate) SetMonthlyPayment(f float64) *SimulationCreate {
	sc.mutation.SetMonthlyPayment(f)
	return sc
}

// SetCreatedAt sets the "created_at" field.
func (sc *SimulationCreate) SetCreatedAt(t time.Time) *SimulationCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *SimulationCreate) SetNillableCreatedAt(t *time.Time) *SimulationCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// Mutation returns the SimulationMutation object of the builder.
func (sc *SimulationCreate) Mutation() *SimulationMutation {
	return sc.mutation
}

// Save creates the Simulation in the database.
func (sc *SimulationCreate) Save(ctx context.Context) (*Simulation, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SimulationCreate) SaveX(ctx context.Context) *Simulation {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SimulationCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SimulationCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SimulationCreate) defaults() {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := simulation.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SimulationCreate) check() error {
	if _, ok := sc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Simulation.amount"`)}
	}
	if _, ok := sc.mutation.Interest(); !ok {
		return &ValidationError{Name: "interest", err: errors.New(`ent: missing required field "Simulation.interest"`)}
	}
	if _, ok := sc.mutation.Periods(); !ok {
		return &ValidationError{Name: "periods", err: errors.New(`ent: missing required field "Simulation.periods"`)}
	}
	if _, ok := sc.mutation.MonthlyPayment(); !ok {
		return &ValidationError{Name: "monthly_payment", err: errors.New(`ent: missing required field "Simulation.monthly_payment"`)}
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Simulation.created_at"`)}
	}
	return nil
}

func (sc *SimulationCreate) sqlSave(ctx context.Context) (*Simulation, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SimulationCreate) createSpec() (*Simulation, *sqlgraph.CreateSpec) {
	var (
		_node = &Simulation{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(simulation.Table, sqlgraph.NewFieldSpec(simulation.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.Amount(); ok {
		_spec.SetField(simulation.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := sc.mutation.Interest(); ok {
		_spec.SetField(simulation.FieldInterest, field.TypeFloat64, value)
		_node.Interest = value
	}
	if value, ok := sc.mutation.Periods(); ok {
		_spec.SetField(simulation.FieldPeriods, field.TypeFloat64, value)
		_node.Periods = value
	}
	if value, ok := sc.mutation.MonthlyPayment(); ok {
		_spec.SetField(simulation.FieldMonthlyPayment, field.TypeFloat64, value)
		_node.MonthlyPayment = value
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(simulation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// SimulationCreateBulk is the builder for creating many Simulation entities in bulk.
type SimulationCreateBulk struct {
	config
	err      error
	builders []*SimulationCreate
}

// Save creates the Simulation entities in the database.
func (scb *SimulationCreateBulk) Save(ctx context.Context) ([]*Simulation, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Simulation, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SimulationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SimulationCreateBulk) SaveX(ctx context.Context) []*Simulation {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SimulationCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SimulationCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
