// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Simulation is the predicate function for simulation builders.
type Simulation func(*sql.Selector)
